// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebLego.DataSet.GdrService;

#nullable disable

namespace WebLego.Migrations
{
    [DbContext(typeof(DbpouletLgv5Context))]
    partial class DbpouletLgv3ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductUser", b =>
                {
                    b.Property<int>("ProductsProductId")
                        .HasColumnType("int");

                    b.Property<int>("UsersUserId")
                        .HasColumnType("int");

                    b.HasKey("ProductsProductId", "UsersUserId");

                    b.HasIndex("UsersUserId");

                    b.ToTable("ProductUser");
                });

            modelBuilder.Entity("WebLego.DataSet.GdrService.AboutUsSection", b =>
                {
                    b.Property<int>("SectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SectionId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SectionId")
                        .HasName("PK__AboutUsSections__SectionId");

                    b.HasIndex("CreatedBy");

                    b.ToTable("AboutUsSections");
                });

            modelBuilder.Entity("WebLego.DataSet.GdrService.Cart", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CartID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartId"));

                    b.Property<DateTime?>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("ProductID");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("CartId")
                        .HasName("PK__Cart__51BCD7975C1840AB");

                    b.HasIndex("ProductId");

                    b.HasIndex(new[] { "UserId", "ProductId" }, "UQ_Cart_User_Product")
                        .IsUnique();

                    b.ToTable("Cart", (string)null);
                });

            modelBuilder.Entity("WebLego.DataSet.GdrService.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.HasKey("CategoryId")
                        .HasName("PK__Categori__19093A0BC0C9FB4E");

                    b.HasIndex("CreatedBy");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("WebLego.DataSet.GdrService.CommunityComment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentId"));

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("IsFlagged")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CommentId")
                        .HasName("PK__CommunityComments__CommentId");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("CommunityComments");
                });

            modelBuilder.Entity("WebLego.DataSet.GdrService.CommunityPost", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostId"));

                    b.Property<int>("CommentCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("ContestId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsFlagged")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PostId")
                        .HasName("PK__CommunityPosts__PostId");

                    b.HasIndex("ContestId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("CommunityPosts");
                });

            modelBuilder.Entity("WebLego.DataSet.GdrService.ContactInformation", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContactId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ContactId")
                        .HasName("PK__ContactInformations__ContactId");

                    b.HasIndex("CreatedBy");

                    b.ToTable("ContactInformations");
                });

            modelBuilder.Entity("WebLego.DataSet.GdrService.Contest", b =>
                {
                    b.Property<int>("ContestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContestId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ContestId")
                        .HasName("PK__Contests__ContestId");

                    b.HasIndex("CreatedBy");

                    b.ToTable("Contests");
                });

            modelBuilder.Entity("WebLego.DataSet.GdrService.ContestVote", b =>
                {
                    b.Property<int>("VoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VoteId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("VoteId")
                        .HasName("PK__ContestVotes__VoteId");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "PostId", "UserId" }, "UQ_ContestVotes_Post_User")
                        .IsUnique();

                    b.ToTable("ContestVotes");
                });

            modelBuilder.Entity("WebLego.DataSet.GdrService.ContestWinner", b =>
                {
                    b.Property<int>("WinnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WinnerId"));

                    b.Property<int>("ContestId")
                        .HasColumnType("int");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("RewardProductId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Chưa gửi");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("WonAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("WinnerId")
                        .HasName("PK__ContestWinners__WinnerId");

                    b.HasIndex("OrderId");

                    b.HasIndex("RewardProductId");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "ContestId" }, "UQ_ContestWinners_Contest")
                        .IsUnique();

                    b.ToTable("ContestWinners");
                });

            modelBuilder.Entity("WebLego.DataSet.GdrService.CustomerProfile", b =>
                {
                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("CustomerRank")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DiscountCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("CustomerId")
                        .HasName("PK__Customer__A4AE64D80062C105");

                    b.ToTable("CustomerProfiles", t =>
                        {
                            t.HasTrigger("trg_ValidateCustomerRole");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("WebLego.DataSet.GdrService.Favorite", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("Favorites", (string)null);
                });

            modelBuilder.Entity("WebLego.DataSet.GdrService.HomeBanner", b =>
                {
                    b.Property<int>("BannerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BannerId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("BannerId")
                        .HasName("PK__HomeBann__32E86AD10A464E43");

                    b.HasIndex("CreatedBy");

                    b.ToTable("HomeBanners");
                });

            modelBuilder.Entity("WebLego.DataSet.GdrService.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Discount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10, 2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime?>("OrderDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("OrderStatus")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Chờ xác nhận");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PaymentStatus")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Chưa thanh toán");

                    b.Property<int?>("ShipperId")
                        .HasColumnType("int");

                    b.Property<decimal?>("ShippingFee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10, 2)")
                        .HasDefaultValue(15000m);

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("VnpTransactionDate")
                        .HasColumnType("datetime");

                    b.Property<string>("VnpTransactionNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("OrderId")
                        .HasName("PK__Orders__C3905BCFB6D3C544");

                    b.HasIndex("AddressId");

                    b.HasIndex("ShipperId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders", t =>
                        {
                            t.HasTrigger("trg_UpdateRankAndDiscount");

                            t.HasTrigger("trg_UpdateStock_OnOrderCompleted");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("WebLego.DataSet.GdrService.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderDetailId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalPrice")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(21, 2)")
                        .HasComputedColumnSql("([Quantity]*[UnitPrice])", true);

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("OrderDetailId")
                        .HasName("PK__OrderDet__D3B9D36C0598E863");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("WebLego.DataSet.GdrService.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("AgeRange")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<decimal?>("DiscountPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<bool?>("IsFeatured")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("PieceCount")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("ProductDes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProductStatus")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Hoạt động");

                    b.Property<int?>("PromotionId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Rating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(2, 1)")
                        .HasDefaultValue(0m);

                    b.Property<int?>("Sold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("StockQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("ProductId")
                        .HasName("PK__Products__B40CC6CDAD639000");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("PromotionId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("WebLego.DataSet.GdrService.ProductImage", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageId"));

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("IsMain")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("ImageId")
                        .HasName("PK__ProductI__7516F70CAC4425F1");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("WebLego.DataSet.GdrService.ProductReturn", b =>
                {
                    b.Property<int>("ReturnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReturnId"));

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("RequestType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("RequestedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("ReturnStatus")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Đang xử lý");

                    b.Property<decimal?>("TotalRefundAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ReturnId")
                        .HasName("PK__ProductR__F445E9A8A07C06CE");

                    b.HasIndex("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("ProductReturns");
                });

            modelBuilder.Entity("WebLego.DataSet.GdrService.ProductReview", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<string>("AdminReply")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AdminReplyAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("IsFlagged")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("ReviewStatus")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Chưa phản hồi");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ReviewId")
                        .HasName("PK__ProductR__74BC79CE394E2AD2");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.HasIndex(new[] { "UserId", "ProductId", "OrderId" }, "UQ_ProductReviews_User_Product_Order")
                        .IsUnique()
                        .HasFilter("[OrderId] IS NOT NULL");

                    b.ToTable("ProductReviews", t =>
                        {
                            t.HasTrigger("trg_UpdateProductRating");

                            t.HasCheckConstraint("CK_ProductReviews_ReviewStatus", "ReviewStatus IN (N'Chưa phản hồi', N'Đã phản hồi', N'Bị ẩn')");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("WebLego.DataSet.GdrService.Promotion", b =>
                {
                    b.Property<int>("PromotionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PromotionId"));

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<string>("PromotionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PromotionId")
                        .HasName("PK__Promotio__52C42FCFEE8EC12F");

                    b.ToTable("Promotions");
                });

            modelBuilder.Entity("WebLego.DataSet.GdrService.ReturnDetail", b =>
                {
                    b.Property<int>("ReturnDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReturnDetailId"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReplacementProductId")
                        .HasColumnType("int");

                    b.Property<int>("ReturnId")
                        .HasColumnType("int");

                    b.HasKey("ReturnDetailId")
                        .HasName("PK__ReturnDe__8B89C98A37BAE035");

                    b.HasIndex("ProductId");

                    b.HasIndex("ReplacementProductId");

                    b.HasIndex("ReturnId");

                    b.ToTable("ReturnDetails");
                });

            modelBuilder.Entity("WebLego.DataSet.GdrService.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId")
                        .HasName("PK__Roles__8AFACE1ABDA23BAC");

                    b.HasIndex(new[] { "RoleName" }, "UQ__Roles__8A2B616057421610")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("WebLego.DataSet.GdrService.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Phone")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("UserPassword")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserStatus")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Hoạt động");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CC4C9289ACB7");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D105344E20A12A")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WebLego.DataSet.GdrService.UserAddress", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddressId"));

                    b.Property<string>("AddressType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SpecificAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Ward")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AddressId")
                        .HasName("PK__UserAddr__091C2AFB82FBD5D5");

                    b.HasIndex("UserId");

                    b.ToTable("UserAddresses");
                });

            modelBuilder.Entity("ProductUser", b =>
                {
                    b.HasOne("WebLego.DataSet.GdrService.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebLego.DataSet.GdrService.User", null)
                        .WithMany()
                        .HasForeignKey("UsersUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebLego.DataSet.GdrService.AboutUsSection", b =>
                {
                    b.HasOne("WebLego.DataSet.GdrService.User", "CreatedByNavigation")
                        .WithMany("AboutUsSections")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("FK__AboutUsSections__CreatedBy__Users");

                    b.Navigation("CreatedByNavigation");
                });

            modelBuilder.Entity("WebLego.DataSet.GdrService.Cart", b =>
                {
                    b.HasOne("WebLego.DataSet.GdrService.Product", "Product")
                        .WithMany("Carts")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK__Cart__ProductID__6383C8BA");

                    b.HasOne("WebLego.DataSet.GdrService.User", "User")
                        .WithMany("Carts")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Cart__UserID__628FA481");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebLego.DataSet.GdrService.Category", b =>
                {
                    b.HasOne("WebLego.DataSet.GdrService.User", "CreatedByNavigation")
                        .WithMany("Categories")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("FK__Categorie__Creat__45F365D3");

                    b.Navigation("CreatedByNavigation");
                });

            modelBuilder.Entity("WebLego.DataSet.GdrService.CommunityComment", b =>
                {
                    b.HasOne("WebLego.DataSet.GdrService.CommunityPost", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .IsRequired()
                        .HasConstraintName("FK__CommunityComments__PostId__CommunityPosts");

                    b.HasOne("WebLego.DataSet.GdrService.User", "User")
                        .WithMany("CommunityComments")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__CommunityComments__UserId__Users");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebLego.DataSet.GdrService.CommunityPost", b =>
                {
                    b.HasOne("WebLego.DataSet.GdrService.Contest", "Contest")
                        .WithMany("CommunityPosts")
                        .HasForeignKey("ContestId")
                        .HasConstraintName("FK__CommunityPosts__ContestId__Contests");

                    b.HasOne("WebLego.DataSet.GdrService.Order", "Order")
                        .WithMany("CommunityPosts")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK__CommunityPosts__OrderId__Orders");

                    b.HasOne("WebLego.DataSet.GdrService.Product", "Product")
                        .WithMany("CommunityPosts")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK__CommunityPosts__ProductId__Products");

                    b.HasOne("WebLego.DataSet.GdrService.User", "User")
                        .WithMany("CommunityPosts")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__CommunityPosts__UserId__Users");

                    b.Navigation("Contest");

                    b.Navigation("Order");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebLego.DataSet.GdrService.ContactInformation", b =>
                {
                    b.HasOne("WebLego.DataSet.GdrService.User", "CreatedByNavigation")
                        .WithMany("ContactInformations")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("FK__ContactInformations__CreatedBy__Users");

                    b.Navigation("CreatedByNavigation");
                });

            modelBuilder.Entity("WebLego.DataSet.GdrService.Contest", b =>
                {
                    b.HasOne("WebLego.DataSet.GdrService.User", "CreatedByNavigation")
                        .WithMany("Contests")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("FK__Contests__CreatedBy__Users");

                    b.Navigation("CreatedByNavigation");
                });

            modelBuilder.Entity("WebLego.DataSet.GdrService.ContestVote", b =>
                {
                    b.HasOne("WebLego.DataSet.GdrService.CommunityPost", "Post")
                        .WithMany("ContestVotes")
                        .HasForeignKey("PostId")
                        .IsRequired()
                        .HasConstraintName("FK__ContestVotes__PostId__CommunityPosts");

                    b.HasOne("WebLego.DataSet.GdrService.User", "User")
                        .WithMany("ContestVotes")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__ContestVotes__UserId__Users");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebLego.DataSet.GdrService.ContestWinner", b =>
                {
                    b.HasOne("WebLego.DataSet.GdrService.Contest", "Contest")
                        .WithOne()
                        .HasForeignKey("WebLego.DataSet.GdrService.ContestWinner", "ContestId")
                        .IsRequired()
                        .HasConstraintName("FK__ContestWinners__ContestId__Contests");

                    b.HasOne("WebLego.DataSet.GdrService.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__ContestWinners__OrderId__Orders");

                    b.HasOne("WebLego.DataSet.GdrService.Product", "RewardProduct")
                        .WithMany()
                        .HasForeignKey("RewardProductId")
                        .IsRequired()
                        .HasConstraintName("FK__ContestWinners__RewardProductId__Products");

                    b.HasOne("WebLego.DataSet.GdrService.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__ContestWinners__UserId__Users");

                    b.Navigation("Contest");

                    b.Navigation("Order");

                    b.Navigation("RewardProduct");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebLego.DataSet.GdrService.CustomerProfile", b =>
                {
                    b.HasOne("WebLego.DataSet.GdrService.User", "Customer")
                        .WithOne("CustomerProfile")
                        .HasForeignKey("WebLego.DataSet.GdrService.CustomerProfile", "CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK__CustomerP__Custo__4222D4EF");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("WebLego.DataSet.GdrService.Favorite", b =>
                {
                    b.HasOne("WebLego.DataSet.GdrService.Product", "Product")
                        .WithMany("Favorites")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_Favorites_Products");

                    b.HasOne("WebLego.DataSet.GdrService.User", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Favorites_Users");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebLego.DataSet.GdrService.HomeBanner", b =>
                {
                    b.HasOne("WebLego.DataSet.GdrService.User", "CreatedByNavigation")
                        .WithMany("HomeBanners")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("FK__HomeBanne__Creat__123EB7A3");

                    b.Navigation("CreatedByNavigation");
                });

            modelBuilder.Entity("WebLego.DataSet.GdrService.Order", b =>
                {
                    b.HasOne("WebLego.DataSet.GdrService.UserAddress", "Address")
                        .WithMany("Orders")
                        .HasForeignKey("AddressId")
                        .IsRequired()
                        .HasConstraintName("FK_Orders_Addresses");

                    b.HasOne("WebLego.DataSet.GdrService.User", "Shipper")
                        .WithMany("OrderShippers")
                        .HasForeignKey("ShipperId")
                        .HasConstraintName("FK_Orders_Shipper");

                    b.HasOne("WebLego.DataSet.GdrService.User", "User")
                        .WithMany("OrderUsers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Orders_Users");

                    b.Navigation("Address");

                    b.Navigation("Shipper");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebLego.DataSet.GdrService.OrderDetail", b =>
                {
                    b.HasOne("WebLego.DataSet.GdrService.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK__OrderDeta__Order__778AC167");

                    b.HasOne("WebLego.DataSet.GdrService.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK__OrderDeta__Produ__787EE5A0");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WebLego.DataSet.GdrService.Product", b =>
                {
                    b.HasOne("WebLego.DataSet.GdrService.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK__Products__Catego__4F7CD00D");

                    b.HasOne("WebLego.DataSet.GdrService.User", "CreatedByNavigation")
                        .WithMany("ProductsNavigation")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("FK__Products__Create__5070F446");

                    b.HasOne("WebLego.DataSet.GdrService.Promotion", "Promotion")
                        .WithMany("Products")
                        .HasForeignKey("PromotionId")
                        .HasConstraintName("FK_Products_Promotions");

                    b.Navigation("Category");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("WebLego.DataSet.GdrService.ProductImage", b =>
                {
                    b.HasOne("WebLego.DataSet.GdrService.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK__ProductIm__Produ__59063A47");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WebLego.DataSet.GdrService.ProductReturn", b =>
                {
                    b.HasOne("WebLego.DataSet.GdrService.Order", "Order")
                        .WithMany("ProductReturns")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK__ProductRe__Order__7F2BE32F");

                    b.HasOne("WebLego.DataSet.GdrService.User", "User")
                        .WithMany("ProductReturns")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__ProductRe__UserI__00200768");

                    b.Navigation("Order");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebLego.DataSet.GdrService.ProductReview", b =>
                {
                    b.HasOne("WebLego.DataSet.GdrService.Order", "Order")
                        .WithMany("ProductReviews")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK__ProductRe__Order__0D7A0286");

                    b.HasOne("WebLego.DataSet.GdrService.Product", "Product")
                        .WithMany("ProductReviews")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK__ProductRe__Produ__0C85DE4D");

                    b.HasOne("WebLego.DataSet.GdrService.User", "User")
                        .WithMany("ProductReviews")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__ProductRe__UserI__0B91BA14");

                    b.Navigation("Order");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebLego.DataSet.GdrService.ReturnDetail", b =>
                {
                    b.HasOne("WebLego.DataSet.GdrService.Product", "Product")
                        .WithMany("ReturnDetailProducts")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK__ReturnDet__Produ__03F0984C");

                    b.HasOne("WebLego.DataSet.GdrService.Product", "ReplacementProduct")
                        .WithMany("ReturnDetailReplacementProducts")
                        .HasForeignKey("ReplacementProductId")
                        .HasConstraintName("FK__ReturnDet__Repla__04E4BC85");

                    b.HasOne("WebLego.DataSet.GdrService.ProductReturn", "Return")
                        .WithMany("ReturnDetails")
                        .HasForeignKey("ReturnId")
                        .IsRequired()
                        .HasConstraintName("FK__ReturnDet__Retur__02FC7413");

                    b.Navigation("Product");

                    b.Navigation("ReplacementProduct");

                    b.Navigation("Return");
                });

            modelBuilder.Entity("WebLego.DataSet.GdrService.User", b =>
                {
                    b.HasOne("WebLego.DataSet.GdrService.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK__Users__RoleId__3E52440B");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("WebLego.DataSet.GdrService.UserAddress", b =>
                {
                    b.HasOne("WebLego.DataSet.GdrService.User", "User")
                        .WithMany("UserAddresses")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__UserAddre__UserI__693CA210");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebLego.DataSet.GdrService.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("WebLego.DataSet.GdrService.CommunityPost", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("ContestVotes");
                });

            modelBuilder.Entity("WebLego.DataSet.GdrService.Contest", b =>
                {
                    b.Navigation("CommunityPosts");
                });

            modelBuilder.Entity("WebLego.DataSet.GdrService.Order", b =>
                {
                    b.Navigation("CommunityPosts");

                    b.Navigation("OrderDetails");

                    b.Navigation("ProductReturns");

                    b.Navigation("ProductReviews");
                });

            modelBuilder.Entity("WebLego.DataSet.GdrService.Product", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("CommunityPosts");

                    b.Navigation("Favorites");

                    b.Navigation("OrderDetails");

                    b.Navigation("ProductImages");

                    b.Navigation("ProductReviews");

                    b.Navigation("ReturnDetailProducts");

                    b.Navigation("ReturnDetailReplacementProducts");
                });

            modelBuilder.Entity("WebLego.DataSet.GdrService.ProductReturn", b =>
                {
                    b.Navigation("ReturnDetails");
                });

            modelBuilder.Entity("WebLego.DataSet.GdrService.Promotion", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("WebLego.DataSet.GdrService.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("WebLego.DataSet.GdrService.User", b =>
                {
                    b.Navigation("AboutUsSections");

                    b.Navigation("Carts");

                    b.Navigation("Categories");

                    b.Navigation("CommunityComments");

                    b.Navigation("CommunityPosts");

                    b.Navigation("ContactInformations");

                    b.Navigation("ContestVotes");

                    b.Navigation("Contests");

                    b.Navigation("CustomerProfile");

                    b.Navigation("Favorites");

                    b.Navigation("HomeBanners");

                    b.Navigation("OrderShippers");

                    b.Navigation("OrderUsers");

                    b.Navigation("ProductReturns");

                    b.Navigation("ProductReviews");

                    b.Navigation("ProductsNavigation");

                    b.Navigation("UserAddresses");
                });

            modelBuilder.Entity("WebLego.DataSet.GdrService.UserAddress", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
